repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.9.0
    hooks:
    -   id: pre-commit-update
-   repo: https://github.com/pappasam/toml-sort/
    rev: v0.24.4
    hooks:
    -   id: toml-sort-fix
        args: [--in-place]
        exclude: uv.lock
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
    -   id: ruff-format
    -   id: ruff-check
        args: [--fix]
-   repo: local
    hooks:
    -   id: mypy
        entry: uv run mypy .
        language: system
        name: mypy
        pass_filenames: false
        types: [python]
